en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Hardware City. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "Hardware City"
  description: "Build things with people"
  params:
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Discord" # TODO @dvcorreia: point to our slack
      link: "https://discord.gg/vGdXVRgM"
    footer_cta:
      text: "Discord"
      link: "https://discord.gg/vGdXVRgM"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/example-page/"
      weight: 1
    - identifier: "who-we-are"
      name: "Who we are"
      url: "/who-we-are"
      weight: 1
      post: "Hardware City is an association dedicating to build things with people."
      parent: "about"
    - identifier: "members"
      name: "Members"
      url: "/members"
      weight: 2
      post: "We are team of awesome people."
      parent: "about"
    - identifier: "governance"
      name: "Governance"
      url: "/governance"
      weight: 3
      post: "The governance defines how decisions are made, so you can have a feel on how we work."
      parent: "about"
    - identifier: "projects"
      name: "Projects"
      url: "/projects/"
      weight: 2
    - identifier: "sunset-hackathon"
      name: "Sunset Hackathon üåÖ"
      url: "/hackathons/"
      weight: 2
      post: "72 hour marathon focused on the creation of innovative solutions."
      parent: "projects"
    - identifier: "space-maker-space"
      name: "Space Maker Space üõ∏"
      url: "/space-maker-space"
      weight: 3
      post: "A maker space open to you and your projects."
      parent: "projects"
    # - identifier: "companies-directory"
    #   name: "Companies Directory üìÅ"
    #   url: "/companies-directory"
    #   weight: 4
    #   post: "A list of portuguese companies that we have been assembling for the past years."
    #   parent: "projects"
    # - identifier: "other-projects"
    #   name: "Other Projects"
    #   url: "/projects/"
    #   weight: 5
    #   post: "We have been here for a while. Check our older projects!"
    #   parent: "projects"
    - identifier: "sessions"
      name: "Sessions"
      url: "/sessions/"
      weight: 3
    # - identifier: "faq"
    #   name: "FAQs"
    #   url: "/faq/"
    #   weight: 4
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 5
pt:
  languageName: Portugu√™s
  contentDir: content/pt
  weight: 2
  title: "Hardware City"
  description: "Descripci√≥n del Sitio"
  menu:
    main:
    - identifier: "about"
      name: "Acerca de"
      url: "/example-page/"
      weight: 1
    - identifier: "child-1"
      name: "P√°gina Hija de Ejemplo"
      url: "/example-page/"
      weight: 1
      parent: "about"
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
